stages：
	- build
	- test
	- deploy

job1:
	stage: build
	tags:
		- demo
	script:
		- echo "I am job1"
		- echo "I am build stage"
job2:
	stage: test
	tags:
		- demo
	script:
		- echo "I am job2"
		- echo "I am test stage"
job3:
	stage: deploy
	tags:
		- demo
	script:
		- echo "I am job3"
		- echo "I am deploy stage"